### ISSUE TITLE
how to build the css and js dist

### ISSUE THREAD

**Issue by mckaygerhard** [Trekky12/JSTable#1]
any info how to build the production minified js and css final files?

can be used firectly the js in the src directory?

the css can be build/make separately from the js?

**Comment by Trekky12** [comment]
I used Koala (http://koala-app.com/) to minify the css and Javascript. But every minifier can be used. 

The files in src can also be used directly in a supported browser.

I'm using ES6 classes (https://caniuse.com/#feat=es6-class), promises(https://caniuse.com/#feat=promises) and querySelector(https://caniuse.com/#feat=queryselector), so please check if your browser supports these features.

**Comment by imzza** [comment]
Use webpack or gulp Js create production build use any online tool to minify the CSS and JS code.

**Comment by mckaygerhard** [comment]
i'm talking about unminify .. so src js file can be used directly .. i assume you are refering the javscrip code.. ... due the shito of the ES6 theres a huge range of unsuported things.. so this are not usable to anybody only for fashioned.. seems vanilla datatables are the only good thing or then use jquery ones!

> The files in src can also be used directly in a supported browser.

sounds funny "a supported browser", today means only fasioned only!

> I'm using ES6 classes (https://caniuse.com/#feat=es6-class), promises(https://caniuse.com/#feat=promises) and querySelector(https://caniuse.com/#feat=queryselector), so please check if your browser supports these features.

again browser supported etc etc fashion things

**Comment by Trekky12** [comment]
If you are interested I could add a gulp task to transpile the js with babel to be compatible with several browser

**Comment by Trekky12** [comment]
With the latest commit cf676e812200e1f0be787882f71a86a77e86c175 I've optimized the code and included various polyfills.
These files can be easily generated with the underlying `gulpfile` by running the task `gulp sass` for the css and `gulp uglify` for the JavaScript.

Now almost every browser should be supported. Please let me know if there is an error with a specific browser.
