### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by Junglefish** [Trekky12/JSTable#5]
Hi Trekky
In JSTable, is there a hook I can use to default load the table at a page that is not the first page?
I was hoping to find something like the page(n) function in dataTables (https://datatables.net/reference/api/page()).

**Comment by Trekky12** [comment]
Hey @Junglefish, 

you could trigger the pagination manually by manipulating the currentPage attribute and updating the table:
```
let mytable = new JSTable('#table');
table.currentPage = 5;
table.update();
```

but I could include a custom function `paginate(n)`.

**Comment by Junglefish** [comment]
Hi
That's perfect - exactly what I was looking for.
Is there an equivalent for also setting the text in the search box? Something like table.searchBox = "my value"; ?

**Comment by Trekky12** [comment]
What exactly do you mean with the text in the search box? Do you want to trigger the search or do you want to prefill the search box with text (no search submitted)?

I didn't test it but I think calling the `search` method e.g. `table.search("query")` should work.

**Comment by Junglefish** [comment]
Hi Trekky
Yes, again that works perfectly. Just one more small thing though. Even though _table.search("query")_ filters the recordset correctly it would be nice if "query" could actually be displayed in the input box. I've been trying to access that field though the DOM but can't quite find it. Any thoughts?

**Comment by Trekky12** [comment]
Hey @Junglefish, 

You could query for the CSS class `dt-input` which is assigned to the input field:

```
let searchfield = document.querySelectorAll('.dt-input');
searchfield.value = 'query';
```

You could change the css classes name by setting the corresponding value (https://github.com/Trekky12/JSTable/blob/master/src/jstable.js#L26) in the config:
```
new JSTable("#table", {
    classes: {
        input: "dt-input"
    }
});
```

**Comment by Junglefish** [comment]
Hi Trekky

Yep, that does it, although with a slight modification. I needed to do this to make it work:

let searchfield = document.querySelectorAll('.dt-input')**[0]**;
searchfield.value = 'query';

**Comment by Trekky12** [comment]
Oh yes sure, my fault :hushed:

When using `document.querySelectorAll()` all elements are returned and you need the mentioned modification.
Alternatively you could use `document.querySelector('.dt-input')` to get the first element. :smile:

**Comment by Junglefish** [comment]
Hi Trekky
One more question if I may?
When setting the properties of the table, this is fine:
				myTable.search("");		
				myTable.currentPage = 1; 
				myTable.update();

However, what are the object names for these three items?
				myTable.??? = 0;			// sortColumn
				myTable.??? = "asc";		// sortDirection
				myTable.???  = 10; 			// noRecsPerPage

**Comment by Trekky12** [comment]
Hey @Junglefish, 
sure no problem.

You can change the sorting with `sort(column, direction, initial = false)` so for example call `myTable.sort(0, 'asc')` to sort by the first column.

When initializing the JSTable you can define how much rows per page you want to have by:
```
new JSTable("#table", {
    perPage: 10,
    perPageSelect: [5, 10, 15, 20, 25],
});
```

**Comment by Junglefish** [comment]
Hi Trekky

Thanks for that.

Is there also a myTable.[_somethingOrOther_] command for setting the rows per page before calling the update() method? I've been guessing at stuff like this, but I'm running out of guesses...

		//myTable.perPage = 10; 		// nope :-)
		//myTable.perPageChange(10); 	// nope :-)

**Comment by Trekky12** [comment]
Yes there is indeed a parameter in the config for that:

```
table.config.perPage = 10;

let select = document.querySelector('.dt-selector');
// or alternatively:
// let select = document.querySelector('.'+table.config.classes.selector);
select.value = 10;

table.update();
```

**Comment by Trekky12** [comment]
I will close this issue since I've updated the documentation with your questions at https://www.haegi.org/jstable/api.html

Feel free to ask in a new issue.

**Comment by yabdab** [comment]
I have a similar question.

I have this in my URL.

`?search=widget&page=4`

While the search query fires on load, the page number is ignored.

Is there something else I need to do to get it to work?

Thanks.

**Comment by Trekky12** [comment]
I can't confirm your problem.
When adding the parameters search and page both are applied as expected:

e. g. https://jstable.github.io/?search=N&page=2
